### ISSUE TITLE
Adding touch?

### ISSUE THREAD

**Issue by Matt2012** [basic-web-components/basic-carousel#1]
In your video tutorial you mentioned adding touch. Have you any pointers on how this might be done?

**Comment by JanMiksovsky** [comment]
@Matt2012 We're actually working on a complete rewrite of this component that will include the addition of touch support. The existing architecture wasn't easy to adapt for touch. If you can wait a bit, we should have something to share in May.

**Comment by Matt2012** [comment]
Great. Will keep my eyes open. Im building a couple of cordova Apps using polymer and I want to have an intro / tour with a swipeable carousel.

**Comment by JanMiksovsky** [comment]
We've just published a preview of the 0.6 of many of the Basic Web Components. These are designed to work with Polymer 0.9 and, soon, Polymer 1.0. Many of the components, including basic-carousel, have been extensively rewritten. (Some lesser-used components haven't been upgraded yet, and still require Polymer 0.5.)

In the case of basic-carousel, the component now supports touch support on Mobile Safari and Chrome Android. We've posted some [early documentation](http://basic-web-components.github.io/basic-web-components/docs/#basic-carousel).

Since carousels come in many styles, we've factored all visible UI elements (notably, arrow buttons on the left and right) out of this component. As the documentation describes, arrow buttons are now an optional UI "accessory" that can be added in markup. If you wish, you can now also add the standard little dots that go along the bottom of the carousel.

We're a week or two away from calling this 0.6 release done, so if you'd like to take a look, please let us know what you think. In the meantime, I think I'll go ahead and close out this issue. Thanks for your patience.
