### ISSUE TITLE
Set slide number with attribute

### ISSUE THREAD

**Issue by kristfal** [basic-web-components/basic-carousel#3]
Would be awesome if we could set a specific slide number through an element attribute.

**Comment by JanMiksovsky** [comment]
I absolutely agree.

I think this worked before, but may have been lost in the port from Polymer 0.5 to 0.8. I'll investigate.

**Comment by JanMiksovsky** [comment]
Fixing this is proving more difficult than expected. It should be possible to say

```
<basic-carousel selected-index="2">
  ...
</basic-carousel>
```

to set the initial value for the selectedIndex property. However, due to the way selectedIndex is defined, Polymer ignores attempts to set an initial value through an attribute.

I've filed a [Polymer issue](https://github.com/Polymer/polymer/issues/2454) to see what they would recommend. In the meantime, I'll try to find a workaround.

**Comment by JanMiksovsky** [comment]
This has been fixed on the master branch of the consolidated basic-web-components repository. The fix will show up here on the individual basic-carousel repo in the next Basic Web Components release.

Note that the fix is just a workaround. It would be nice to have a more elegant solution, but for now I hope this will suffice.
